### ISSUE TITLE
process_partial_cri error="undefined method `split' for nil:NilClass"

### ISSUE THREAD

**Issue by karthiknagraj** [fluent-plugins-nursery/fluent-plugin-concat#119]
#### Problem
Hi, I am seeing the below log in my fluentd container

```
2023-02-17 11:40:02 +0000 [warn]: #0 send an error event to @ERROR: error_class=NoMethodError error="undefined method `split' for nil:NilClass" location="/usr/local/lib/ruby/gems/2.7.0/gems/fluent-plugin-concat-2.5.0/lib/fluent/plugin/filter_concat.rb:286:in `process_partial_cri'" tag="kube.kube-system" time=2023-02-17 11:40:00.745388030 +0000
```

...

#### Steps to replicate

Provide example config and message

#### Expected Behavior

...

#### Your environment

* paste result of ``fluentd --version`` or ``td-agent --version``
```
root [ / ]# fluentd --version
fluentd 1.13.3
```
* plugin version - 2.5.0
[Gemfile.lock.txt](https://github.com/fluent-plugins-nursery/fluent-plugin-concat/files/10766404/Gemfile.lock.txt)

**Comment by daipom** [comment]
That message means `nil` record was passed to this plugin.
The record data may have been broken in the process somewhere before this plugin process.

A similar problem is confirmed: https://github.com/fluent/fluentd/issues/3970

It is confirmed when transferring data between 2 Fluentd, Forwarder(`out_forward`) and Aggregator(`in_forward`).
When a power failure occurs at Forwarder, some buffer files can be broken, and broken data are transferred.

**Comment by daipom** [comment]
Please reopen this if you need.
