### ISSUE TITLE
Can not install last release 

### ISSUE THREAD

**Issue by bwnyasse** [fluent-plugins-nursery/fluent-plugin-concat#21]
I'm using this plugin to build [led](https://github.com/bwnyasse/led) . I've noticed that you've released **v1.0.0** and **v2.0.0** recently. I've got the following error 

<pre>
Building native extensions.  This could take a while...
ERROR:  Error installing fluent-plugin-concat:
	ERROR: Failed to build gem native extension.

    current directory: /root/.gem/ruby/2.3.0/gems/msgpack-1.0.0/ext/msgpack
/usr/bin/ruby -r ./siteconf20161007-13-147n85y.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /root/.gem/ruby/2.3.0/gems/msgpack-1.0.0 for inspection.
Results logged to /root/.gem/ruby/2.3.0/extensions/x86_64-linux/2.3.0/msgpack-1.0.0/gem_make.out
</pre>

I've resolved the error by sticking with version 0.6.2 like this 

**gem install fluent-plugin-concat -v 0.6.2**

Any ideas ?
Thank.

**Comment by okkez** [comment]
How to set up your environment?
Did you install gems by `gem install`?
Could you copy and paste commands you've executed?

The log said `/usr/lib/ruby/include/ruby.h` is missing while building msgpack-ruby 1.0.0.
So, I think fluent-plugin-concat is not related to your issue.

BTW, I recommend [bundler](http://bundler.io/).
You can lock your gem versions via Gemfile and Gemfile.lock.

**Comment by bwnyasse** [comment]
I've found the error , in fact your plugin **fluent-plugin-concat** in version [2.0.0](https://rubygems.org/gems/fluent-plugin-concat/versions/2.0.0) required at least fluentd v0.14.0  
I'm usind fluentd version 0.12.28
