### ISSUE TITLE
Add configuration option 'multiline_flush_regexp'

### ISSUE THREAD

**Issue by dontub** [fluent-plugins-nursery/fluent-plugin-concat#22]
I request to add the option 'multiline_flush_regexp'. This should be a regular expression that flushes the current multiline event (if any), but is not part of a multiline event itself.

**Comment by okkez** [comment]
Sorry for delay.
I cannot imagine concrete use case. Could you describe concrete use case with real log examples?

**Comment by dontub** [comment]
I'm using [Supervisor](http://supervisord.org/) to start services in a Docker container. In my case it's simplest to print everything to stdout/stderr and use the Docker fluentd logging driver so I also know from which container a message comes. Messages from Supervisor might be multiline. I can recognize by regular expression if a message comes from Supervisor or a service. If a message from a service arrives a possible previous Supervisor multiline message is finished.

**Comment by okkez** [comment]
How about `multiline_start_regexp`?

```
<filter>
  @type concat
  multiline_start_regexp /(supervisord log start line regexp|application log start line)/
</filter>
```

**Comment by dontub** [comment]
This would treat the application log as multiline, too. So I would need to use `flush_interval` and `timeout_label` and additional code to handle the timeout to get the last log. This would make the config unnecessary complicated.

**Comment by okkez** [comment]
@dontub Sorry for delay, could you show me the concrete logs.
I want to know how complex supervisord and application log.

**Comment by okkez** [comment]
No response.
