### ISSUE TITLE
process event as normal after flush_interval

### ISSUE THREAD

**Issue by vladm** [fluent-plugins-nursery/fluent-plugin-concat#25]
hi,
after flush_interval occurs the plugin generates error event which throws everything off. 
In some cases - like multi-line log with long periods of inactivity - it would be extremely convenient instead to be able to configure plugin to act as like multiline_end_regexp just matched on flush_interval timeout - this would allow normal processing of the lines already in the buffer.

**Comment by okkez** [comment]
Could you describe concrete use case?
I cannot imagine it.

**Comment by vladm** [comment]
We run PostgreSQL containers, sometimes PostgreSQL spits out multi-line messages in the log.  
The time between messages can be hours. Right now I have flush_interval set to a very high value, so it doesn't trigger error, but it seems there should be an easier way.

**Comment by vladm** [comment]
I noticed another issue #8 - he/she is essentially wanting to be able to do the same - flush accumulated message buffer on timeout and process resulting event as normal.

**Comment by okkez** [comment]
Sorry, I confused with other issue.
It is impossible to handle timeout events as normal events.
See #8

**Comment by okkez** [comment]
Duplicated with #8

**Comment by okkez** [comment]
I commented solution idea to #8.
