### ISSUE TITLE
Plugin does not support @label

### ISSUE THREAD

**Issue by r4j4h** [fluent-plugins-nursery/fluent-plugin-concat#35]
The fluentd [out_relabel documentation](http://docs.fluentd.org/v0.12/articles/out_relabel#label) states:

> FYI: All of input and output plugins also have @label parameter provided by Fluentd core. The relabel plugin is a plugin which actually does nothing, but supports only @label parameter.

While this is not a core plugin, nor is it an input or output plugin, it does provide `timeout_label` functionality.

As described [in this issue thread](https://github.com/fluent-plugins-nursery/fluent-plugin-concat/issues/7#issuecomment-274048892) a method is described to grab `timeout_label` captured messages in a similar fashion to non-labelled or otherwise labelled events.

It involves the use of the `relabel` plugin to capture non timeout_label output and label it the same, like so:

```
<filter mything>
    @type concat
    .. snip ..
    timeout_label @NORMAL
</filter>

<match **>
    @type relabel
    @label @NORMAL
</match>

<label @NORMAL>
    ... snip ...
</label>
```

I think that this step could be alleviated by enabling this plugin to also handle the `@label` attribute.

This would reduce the above to:

```
<filter mything>
    @type concat
    .. snip ..
    @label @NORMAL
    timeout_label @NORMAL
</filter>

<label @NORMAL>
    ... snip ...
</label>
```

But it appears that this plugin ignores @label, although no warnings seem to appear either, the label does not take effect, requiring the use of the `relabel` plugin for this behavior.

Is this an out of bounds request since this is a filter plugin, or does this seem like it would be a useful addition?

**Comment by okkez** [comment]
Thank you for reporting.

Fluentd's filter plugin ignore `@label`. It is spec of Fluentd's plugin architecture.
"out relabel" is output plugin but "filter concat" is filter plugin not output plugin.
Fluentd's filter plugin cannot rewrite label for each record. It is specification of Fluentd.

**Comment by r4j4h** [comment]
Thanks, I was afraid of that. It makes sense for why the relabelling and tag rewriters are considered output plugins though. I will close this since there is nothing we can do.

Thanks for the quick response!! :) :+1:
