### ISSUE TITLE
Examples would be cool

### ISSUE THREAD

**Issue by erikbgithub** [fluent-plugins-nursery/fluent-plugin-concat#36]
Honestly I still have no idea what this is good for. I come here from the [fluentd docker doc](http://www.fluentd.org/guides/recipes/docker-logging) (chapter: "Additional Step 2: Concatenate multiple lines log messages").

The example given there with `-e:4:in`. I have no idea what it is or does. Please explain.

**Comment by okkez** [comment]
See [README.md](https://github.com/fluent-plugins-nursery/fluent-plugin-concat/blob/master/README.md) and [test code](https://github.com/fluent-plugins-nursery/fluent-plugin-concat/blob/master/test/plugin/test_filter_concat.rb), please.

**Comment by erikbgithub** [comment]
I don't see examples in either. I see configuration variations but not what they do. What's the input? What's the result? What's the **reason**?

**Comment by okkez** [comment]
[documentation](http://www.fluentd.org/guides/recipes/docker-logging) provides input examples.
[README.md](https://github.com/fluent-plugins-nursery/fluent-plugin-concat/blob/master/README.md) describes configuration parameters.
[test code](https://github.com/fluent-plugins-nursery/fluent-plugin-concat/blob/master/test/plugin/test_filter_concat.rb) provides example configuration and input and output.

**Comment by erikbgithub** [comment]
> documentation provides input and configuration examples.
This one is not clear. That's why I created this issue.

> README.md describes configuration parameters.
> test code provides example configuration and input and output.

Why do you repeat that? I already responded to that.

**Comment by cosmo0920** [comment]
> The example given there with -e:4:in. I have no idea what it is or does. Please explain.

This is a mark for an end line to concatenate message with regular expressions.

```log
# start line and the second line contain "-e:2"
2016-04-13 14:45:55 +0900 docker.28cf38e21204: {"container_id":"28cf38e212042225f5f80a56fac08f34c8f0b235e738900c4e0abcf39253a702","container_name":"/romantic_dubinsky","source":"stdout","log":"-e:2:in `/'"}
2016-04-13 14:45:55 +0900 docker.28cf38e21204: {"source":"stdout","log":"-e:2:in `do_division_by_zero'","container_id":"28cf38e212042225f5f80a56fac08f34c8f0b235e738900c4e0abcf39253a702","container_name":"/romantic_dubinsky"}
# Concatinate end line should contain "-e:4"
2016-04-13 14:45:55 +0900 docker.28cf38e21204: {"source":"stdout","log":"-e:4:in `<main>'","container_id":"28cf38e212042225f5f80a56fac08f34c8f0b235e738900c4e0abcf39253a702","container_name":"/romantic_dubinsky"}
```

will concatinate with this plugin:

```log
2016-04-13 14:45:55 +0900 docker.28cf38e21204: {"container_id":"28cf38e212042225f5f80a56fac08f34c8f0b235e738900c4e0abcf39253a702","container_name":"/romantic_dubinsky","source":"stdout","log":"-e:2:in `/'\n-e:2:in `do_division_by_zero'\n-e:4:in `<main>'"}
```

I'm wondering why these examples are hard to understand for you.

Do you want to concatenate log such as one by one Fluentd Docker drivers'?
Or just want to try to follow [the above article](http://www.fluentd.org/guides/recipes/docker-logging)?
If you tell us what you want to do with this plugin, it would be able to solve your question more easily.

**Comment by erikbgithub** [comment]
Yeah, I'm just going through the article you linked and try to understand what they write there. I never felt a reason to concat log messages. Usually it's convenient that they are each on their own line.

The only usecase I can think off myself that may or may not go into a similar direction is for instance nginx reporting 150x "I got a request from client 1.2.3.4 and responded with 200". This could be combined in log aggregation to "I got a request from client 1.2.3.4 and responded with 200 (150x)" in a single line.

**Comment by cosmo0920** [comment]
Our assuming use cases are:

* Concatenate Ruby or other LL multiline stacktrace
* JVM null pointer or something exception multiline stacktrace 
* Golang stack trace

They are in Docker container.

If there is any problem or feedback, you can report as an issue in https://github.com/fluent/fluentd-docs.
