### ISSUE TITLE
Concating by time in brackets

### ISSUE THREAD

**Issue by Falconxx** [fluent-plugins-nursery/fluent-plugin-concat#40]
Hello my logs looks like Error [2018-10-01 15:12:31,323] ! at or INFO [2018-10-01 15:12:31,323] i want to concat them by time in those brackets cause Ofc when im concatting by error or info i get infos in errors or errors in infos, is this possible?

**Comment by okkez** [comment]
Do you mean that you want to concatenate lines which has same timestamp?

Your logs like following?

```
Error [2018-10-01 15:12:31,323] (something goes here)
INFO [2018-10-01 15:12:31,323] (something gose here)
```

Maybe, you can concatenate such logs using [filter_parser](https://docs.fluentd.org/v1.0/articles/filter_parser) and this plugin like following:

```
<source>
  @type tail
  path /path/to/log
  tag test.log
  <parse>
    @type none
  </parse>
</source>

<filter>
  @type parser
  key_name message
  <parse>
    @type regexp
    expression /^(?<level>(?:INFO|Error)) \[(?<timestamp>\d{4}\d{2}-\d{2}- \d{2}:\d{2}:\d{2})\](?<rest>.*)/
  </parse>
</filter>
<filter>
  @type concat
  key message
  stream_identity_key timestamp
 multiline_start_regexp ... # I can't imagine your full logs...
</filter>

<match **>
  @type stdout
</match>
```

But I did not test above configuration at all.

**Comment by Falconxx** [comment]
INFO  [2018-01-10 20:02:56,309] net.axisdata.broq.contracts.CoResources: Contract null enrichment time: 1
INFO  [2018-01-10 20:02:56,310] net.axisdata.broq.contracts.CoResources: upload: SADD co:META dd:co:null, ret:0
INFO  [2018-01-10 20:02:56,311] net.axisdata.broq.contracts.CoResources: upload: HMSET dd:co:null {[B@10e193e=[B@7825cb17, [B@3480e595=[B@3a515f9b}, size:81, ret:OK
ERROR [2018-01-10 20:02:56,312] net.axisdata.broq.contracts.CoResources: upload
! java.lang.NullPointerException: null
! at net.axisdata.broq.contracts.ContractRedisUpload.<init>(ContractRedisUpload.java:161)
! at net.axisdata.broq.contracts.CoResources.upload(CoResources.java:281)
! at net.axisdata.broq.contracts.CoResources.upload(CoResources.java:184)
! at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
! at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
! at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
! at java.lang.reflect.Method.invoke(Method.java:498)
! at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
! at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)
! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
! at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
! at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
! at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
! at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
! at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
! at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
! at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
! at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
! at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
! at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
! at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
! at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
! at io.dropwizard.jetty.NonblockingServletHolder.handle(NonblockingServletHolder.java:49)
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1634)
! at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:34)
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1621)
! at io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:50)
! at io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:44)
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1621)
! at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:541)
! at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
! at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1239)
! at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
! at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:481)
! at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
! at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1141)
! at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
! at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:241)
! at io.dropwizard.jetty.RoutingHandler.handle(RoutingHandler.java:52)
! at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:494)
! at io.dropwizard.jetty.BiDiGzipHandler.handle(BiDiGzipHandler.java:68)
! at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:56)
! at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:169)
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
! at org.eclipse.jetty.server.Server.handle(Server.java:564)
! at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
! at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
! at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
! at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
! at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
! at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
! at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
! at java.lang.Thread.run(Thread.java:748)
INFO  [2018-01-10 20:02:56,312] net.axisdata.broq.contracts.CoResources: upload: cid: null, modified: 2018-01-10T21:02:56.308, time: 4

**Comment by Falconxx** [comment]
and in kibana this !at org are different logs, i want to have them in the ERROR log

**Comment by okkez** [comment]
You can use `continuous_line_regexp` like following.

```
<filter>
  @type concat
  key message
  multiline_start_regexp /^ERROR/
  continuous_line_regexp /^!/
</filter>
```

**Comment by Falconxx** [comment]
but in the difference type of log i got another type of string in the beggining thats why i want to make it by the date format can i just do something like 
   <filter kubernetes.**>
       @type concat
       key log
       stream_identity_key container_id
       multiline_start_regexp /^\[(?<timestamp>\d{4}\d{2}-\d{2}- \d{2}:\d{2}:\d{2})\](?<rest>.*)/
       flush_interval 60 
    </filter>

**Comment by okkez** [comment]
How about following?

```
<filter>
  @type concat
  key message
  multiline_start_regexp /^[A-Z]+ \[\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d{3}\].*/
  continuous_line_regexp /^!/
</filter>
```

**Comment by Falconxx** [comment]
i cant hardcode continous lines like that because not always they start with ! that's why i want to just start new log when he gets \[\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d{3}\].*/

**Comment by Falconxx** [comment]
multiline_start_regexp /\[\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d{3}\].*/ this works thanks

**Comment by okkez** [comment]
Thank you!
