### ISSUE TITLE
Add option to disable logging on timeouts

### ISSUE THREAD

**Issue by xanonid** [fluent-plugins-nursery/fluent-plugin-concat#51]
#### Problem

Some applications write supplementary information to log events
with indented lines. I would like to use the fluent-plugin-concat to join 
these extra log lines with the initial, main line.
Not all log lines have such extra information. 

#### Steps to replicate

I tried
```
    <filter **>
      @type concat
      key message
      multiline_start_regexp /^[^[:space:]]/
      flush_interval 2
      timeout_label @OUTPUT
    </filter>
```
and got lots of "Timeout flush: ..." log messages in fluentd.

#### Wanted Behavior
It would be nice if the timeout case could be optionally handled as a normal case without any extra info logging etc. 

Sidenote: In the https://github.com/GoogleCloudPlatform/fluent-plugin-detect-exceptions plugin, this seems to be implemented for its special case.

**Comment by okkez** [comment]
You can set `@log_level error` to suppress such messages like following:

```
    <filter **>
      @type concat
      @log_level error
      key message
      multiline_start_regexp /^[^[:space:]]/
      flush_interval 2
      timeout_label @OUTPUT
    </filter>
```

Is this enough?

Note that `@log_level error` will also suppress the message "Flush remaining buffer: ...` when shutdown this plugin.

**Comment by okkez** [comment]
No response.

**Comment by donat-b** [comment]
@okkez 
I was trying to understand the root cause of flush timeout errors, looked at the docs but it didn't give me a clear answer. Would you be so kind to elaborate what is timeout flush and why it happens?
Thanks in advance!

**Comment by okkez** [comment]
It is the specification.
I think that users should understand the format of incoming multiline logs.
But sometimes the next line of the log cannot be received though waiting for continuous lines.
(ex. wrong regular expression, unexpected incoming logs, etc.)
If the plugin does not flush halfway logs according to timeout, we cannot see any logs forever.
