### ISSUE TITLE
Concatenating logs results in newline being added

### ISSUE THREAD

**Issue by desaintmartin** [fluent-plugins-nursery/fluent-plugin-concat#56]
When concatenating two logs into one, a newline is appended at the separation between the two logs.

If this log is made of JSON, with bad luck we can have an escaping character (\) just before this newline, making the json parser unable to read it.

This is easily dealt with a record_transformer, but would this be a good feature to do this built-in?

**Comment by desaintmartin** [comment]
Note to self and for future readers : using an empty separator:
```
<filter **>
  @type concat
  key "log"
  multiline_end_regexp "/\\n$/"
  separator ""
</filter>
```

works well. Maybe this could be added to the Docker single line json example?

**Comment by okkez** [comment]
@denniswebb Could you create a PR for this under Usage section in README.md?

**Comment by desaintmartin** [comment]
Added for partial_message. Would you like a PR with Docker versions before 18.06 (without partial_message, i.e my example here)?

**Comment by okkez** [comment]
Yes. It would be better adding documents about Docker versions before 18.06.

**Comment by desaintmartin** [comment]
Done. Note that on my configuration (within AND without kubernetes), the key is not message but log.

**Comment by okkez** [comment]
Thank you!
