### ISSUE TITLE
Concat does not work correctly for partial messages

### ISSUE THREAD

**Issue by vatcher** [fluent-plugins-nursery/fluent-plugin-concat#59]
#### Problem
Partial messages are wrong concatenated. Every partial message part (also the last part) has the flag `partial_message` = true. So it is impossible to concat right partial message even when followed messages are to long and are partitioned. 
It is also not enough to have only one flag, when messages arrive concurrent.  

#### Steps to replicate
docker run --log-driver=fluentd -it perl perl -e 'print "START" ;print "X" x 24000; print "END\n"'

This will log in fluentd for every part of partial message the boolean `partial_message` as true. 

#### Expected Behavior
The plugin should use the partial log meta data [PartialLogMetaData](https://github.com/moby/moby/blob/9c65b2206dbc4d950fcf40f94c9c05bd9130536c/api/types/backend/backend.go#L32) to concat log messages. The current version of docker (moby) does not fill this metadata as you can see [here](https://github.com/moby/moby/blob/d6a7c22f7b9aa028623ef8c7cb31d1bb04dd9d84/daemon/logger/fluentd/fluentd.go#L166). So I created an [issue](https://github.com/moby/moby/issues/37889) to extends this metadata.

**Comment by okkez** [comment]
Thank you for reporting the issue.
I will write a patch for this issue after fix https://github.com/moby/moby/issues/37889.

**Comment by dsouzajude** [comment]
Hi @okkez Thanks for this great plugin :)

Just want to bring to your notice that the metadata fix required by this plugin to properly assemble partial messages was merged to master 3 months ago. 

https://github.com/moby/moby/blob/master/daemon/logger/fluentd/fluentd.go#L166-L171

So maybe now the concat plugin can use the metadata fields to properly reassemble the partial messages. Any plans to write a patch for this? Thanks

**Comment by okkez** [comment]
Thank you for letting me know the update.
I will write the patch for this issue this week.

**Comment by okkez** [comment]
docker 18.09.7 does not include the above changes (parshal_xxx).

**Comment by dsouzajude** [comment]
@okkez  The changes will be released in the 19.03 release, which is currently in the RC phase. I guess you can test your patch with that version as it's downloadable [here](https://github.com/docker/docker-ce/releases/tag/v19.03.0-rc3) :)

**Comment by okkez** [comment]
Oh, thanks!

**Comment by tomola** [comment]
19.03.0 has been released https://github.com/docker/docker-ce/releases.
