### ISSUE TITLE
Concat plugin not concatenating multiple lines

### ISSUE THREAD

**Issue by lp060** [fluent-plugins-nursery/fluent-plugin-concat#64]
#### Problem
Concat not working for multi line on kubernetes environment. I am using fluentd kinesis and concat plugin

I have two scenarios for which its not working

1) Multiline seperated by \n and starting with a time stamp - Only the first line of multiline reaches the destination. Other logs are lost.
Example: Testing line 1 \n Testing line 2\n Testing line3
The log is lost and does not reach the destination
2) Java exception stack trace which is multiple lines - The stack traces are reaching the destination as multiple records and in jumbled. They are not sent as single record after concatenation.

This is my fluentd configuration
```
# concat multiline logs if the first line starts with a date in a specific format
    <filter kubernetes.**>
      @type concat
      key message
      multiline_start_regexp /^\d{4}-\d{1,2}-\d{1,2}/
      stream_identity_key stream
      flush_interval 2
      use_first_timestamp true
      timeout_label @NORMAL
    </filter>
```
I am using concat plugin version 2.3.0

Also, I am not clear with the usage of stream_identity_key. What is it used for?

**Comment by lp060** [comment]
Hello, Anyone please suggest something.

**Comment by okkez** [comment]
Could you show me your logs about both scenarios?

**Comment by MyOldSkyGrandfather** [comment]
dude what happened , how do you solve the second scenario

**Comment by cristianpetrula** [comment]
I am experiencing the same issue. I think is related to the timeout label.
