### ISSUE TITLE
Feature request: new configuration: 'timeout_is_error'

### ISSUE THREAD

**Issue by macdjord** [fluent-plugins-nursery/fluent-plugin-concat#8]
I request that a new configuration option be added, 'timeout_is_error' (type boolean, default true). This option would be such that, if it is set to true, if the flush_interval expires on a buffer, an error event is generated and the content of the buffer is output under the timeout_label label (as is the current behavior), but if it is false, the content of the buffer is emitted as if it had been completed and no error is generated.

I have a number of logs which I process using concat. In each case, I can tell when a new record is starting (because it starts with a timestamp), but have no reliable way of telling when one ends, except by waiting for the next log entry to start. As a result, I get lots of bogus timeout errors from concat. Dealing with this adds a lot of pointless, hard-to-maintain complexity and repetition to my Fluendtd configuration files. It would be _much_ easier if I could just tell concat that no, those timeouts are _not_ errors and it should not treat them as if they were.

**Comment by okkez** [comment]
I will consider this issue in next week.
(I will add new option or ...)

**Comment by macdjord** [comment]
This does not solve my use case. I do not _want_ to wait forever for the next line. In some cases, it could be hours or days before the next line occurs. If 60s go by with no new lines, that's probably it - I want to output what is in the buffer without generating an error.

**Comment by okkez** [comment]
Use `timeout_label` configuration.

**Comment by macdjord** [comment]
That's what I do currently, but it adds a lot of pointless complexity to my config files and generates spurious timeout warning messages. All I want is to output my timeouts the same way other lines are output.

**Comment by MartinsThiago** [comment]
+1

Some time ago I requested the same in #7

**Comment by okkez** [comment]
Hmm...

* Use `timeout_label`
  * :+1: Reduce warnings
  * :-1: Complex duplicated configuration
* Not using `timeout_label`
  * :-1: warnings
  * :-1: Complex duplicated configuration

You want:

* No warnings when timeout occurs
* Need timeout and flush buffer and emit normal event
* No complex duplicated configuration

Right?

**Comment by macdjord** [comment]
Yes. When the timeout happens, just emit whatever's in the buffer, as if a startline had come in.

**Comment by okkez** [comment]
It is impossible to implement such a thing.
It is the limitation of Fluentd.

**Comment by macdjord** [comment]
Er? You already emit the buffer content, directed to timeout_label. Is it really not possible to simply do the same, but direct it to the default label instead?

And it's _definitely_ possible to not emit an error message - just make [line 165](https://github.com/okkez/fluent-plugin-concat/blob/master/lib/fluent/plugin/filter_concat.rb#L165) conditional.

**Comment by okkez** [comment]
It is impossible.
If just call `router.emit`, it skips remained filters defined after filter_concat.

You can set `log_level` per plugin.

```
<filter>
  @type concat
  log_level warn
  # ... snip
</filter>
```

**Comment by freemanh** [comment]
I have a way to work around this issue, but still not perfect:
`multiline_start_regexp /[\d-]+ [\d:.]+ *ERROR/`

so, only error stack trace is printed, the multiline plugin is activated. of course, this config suppose you print stack trace only when error happened.

but this is not perfect as well, because when an error printed, if there is no more preceding logs, this error may not be flushed

**Comment by naerymdan** [comment]
Is there really no way to simply close a multiline capture when timeout is reached and process like normal? A lot of situations (java logs & stacktrace) have no clear multiline end.

The other plugins from fluentd, like the memory buffer ones seems to be able to simply apply a flush interval to their processing, at which point all the collected stuff simply goes on to be processed normally.

**Comment by mindw** [comment]
Something like this:

> multiline_flush_interval
> 
> The interval of flushing the buffer for multiline format. The default is disabled.
> 
> If you set multiline_flush_interval 5s, in_tail flushes buffered event after 5 seconds from last emit. This option is useful when you use format_firstline option. Since v0.12.20 or later.
>

**Comment by okkez** [comment]
> Is there really no way to simply close a multiline capture when timeout is reached and process like normal? 

There is no way.
This plugin is filter, so we cannot emit normal event. In fact, filter cannot emit normal event. It is difference from output plugin.

> The other plugins from fluentd, like the memory buffer ones seems to be able to simply apply a flush interval to their processing, at which point all the collected stuff simply goes on to be processed normally.

Those plugins are output plugin. But this is filter plugin.
We don't use Fluentd's buffer mechanism in this plugin.

**Comment by okkez** [comment]
> Something like this from fluentd 0.12.20+:

Fluentd's `in_tail` is input plugin, but this is filter plugin.

If disable timeout flush like `in_tail`, we cannot receive next event forever when input source (such as docker log driver via in_forward) is blocked.

**Comment by mindw** [comment]
Got it. An unfortunate fluentd limitation.

**Comment by okkez** [comment]
I've got a solution for this issue, but it is not perfect and not implemented.

* Add new configuration `soft_flush_interval`, this counts timeout in main thread
* if Fluentd does not send events to this filter plugin:
  * `soft_flush_interval`: does not flush buffer
  * `flush_interval`: flush buffer and timeout error occur
* if Fluentd sends events but not the end of multline:
  * `soft_flush_interval`: flush buffer as normal events
  * `flush_interval`: flush buffer and timeout error occur (if `soft_flush_interval > flush_interval`: this means `soft_flush_interval` is disabled)
* This solution introduces complexity to this pluigin

**Comment by vladm** [comment]
@okkez this would not really help my case.

**Comment by mdamir** [comment]
A workaround this would be to use the relabel plugin to label in both cases i.e. in case when concat gives timeout and in case when it does not and then, finally putting all your output plugins under that label. Here is an example:
`<filter **>
    @type concat
    key "message"
    multiline_start_regexp "/^Start/"
    flush_interval 5
    timeout_label "@LASTLINE"
  </filter>
  <match **>
    @type relabel
    @label @NORMAL
  </match>
  <label @LASTLINE>
    <match **>
      @type relabel
      @label @NORMAL
    </match>
  </label>
  <label @NORMAL>
    <match **>
      @type stdout
    </match>
  </label>`

**Comment by okkez** [comment]
Thanks you for comments.
I will add this to README.md.

**Comment by macavity23** [comment]
@mdamir 's workaround works nicely! Thanks :)
