### ISSUE TITLE
disable filter chain optimization because [Fluent::Plugin::ConcatFilter] uses filter_stream method

### ISSUE THREAD

**Issue by grosser** [fluent-plugins-nursery/fluent-plugin-concat#95]
seeing this in the logs
```
disable filter chain optimization because [Fluent::Plugin::ConcatFilter] uses `#filter_stream` method
```
with v2.4.0 ... is this just something that is fundamentally not possible or fixable ?
/cc @okkez

**Comment by cosmo0920** [comment]
It is impossible to fix it.
We cannot use `#filter` method in this plugin.
Because fluent-plugin-concat requires the previous records information to concatenate them but, inside `#filter` method, we cannot obtain/hold the previous ones.

**Comment by gangefors** [comment]
For people finding this issue and want to disable the *info* output from concat but not from other plugins.
Add `@log_level warn` to set the log level for a specific plugin. Ref. https://docs.fluentd.org/deployment/logging#per-plugin-log
